name: build and publish Image

on: 
  push:
    branches:
      - main
      
jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: build package
        run: python -m http-server &
        
      - name: test http server
        run: curl -I http://localhost:8080
        
      - name: build-image from dockerfile
        run: docker build . --tag test-workflow:v1
        
      - name: publish-image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: dikshash1999/workflows
          username: ${{ secrets.REPO_UNAME }}
          password: ${{ secrets.REPO_PASSWORD }}
    
